name: 'Google Cloud Container Registry Build & Push'
description: 'Build image, authenticate with gcloud, and push image to GCR'
author: 'David Stefan <david@carbonchain.com>'
branding:
  icon: 'arrow-up-circle'
  color: 'green'
inputs:
  project_id:
    description: 'id of your GCP project'
    required: true
  dockerfile:
    description: 'path to your dockerfile'
    required: true
  image:
    description: 'name of the image you want to build and push'
    required: true
  service_account_key:
    description: 'GCP service key with storage and GCR permissions'
    required: true
  context:
    description: 'path to the build context, defaults to . if not provided'
    required: false
  target:
    description: 'which stage to build, if using multistage docker builds'
    required: false
  build_args:
    description: 'list of build args that will be passed to docker build'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
